tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed": "#1f1635",
        "error-container": "#93000a",
        "on-primary-fixed": "#22005d",
        "on-background": "#e6e0e9",
        "on-error": "#690005",
        "on-primary": "#381e72",
        "on-primary-fixed-variant": "#4f378a",
        "surface-container-highest": "#36343a",
        "tertiary-fixed-dim": "#e7c365",
        "secondary": "#cdc0e9",
        "on-surface": "#e6e0e9",
        "on-secondary": "#342b4b",
        "surface-variant": "#36343a",
        "on-primary-container": "#e0d2ff",
        "on-tertiary-fixed-variant": "#594400",
        "on-secondary-fixed-variant": "#4b4263",
        "surface-container-high": "#2b292f",
        "primary": "#cfbcff",
        "surface-container-low": "#1d1b20",
        "tertiary": "#e7c365",
        "surface-dim": "#141218",
        "outline": "#948e9c",
        "tertiary-container": "#c9a74d",
        "primary-fixed": "#e9ddff",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#cdc0e9",
        "on-secondary-container": "#bfb2da",
        "surface-container": "#211f24",
        "on-surface-variant": "#cbc4d2",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e6e0e9",
        "inverse-on-surface": "#322f35",
        "surface-container-lowest": "#0f0d13",
        "secondary-container": "#4d4465",
        "outline-variant": "#494551",
        "error": "#ffb4ab",
        "surface-bright": "#3b383e",
        "on-tertiary-fixed": "#241a00",
        "inverse-primary": "#6750a4",
        "surface-tint": "#cfbcff",
        "on-tertiary": "#3e2e00",
        "tertiary-fixed": "#ffdf93",
        "primary-container": "#6750a4",
        "background": "#141218",
        "surface": "#141218",
        "on-tertiary-container": "#503d00",
        "primary-fixed-dim": "#cfbcff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Anton"],
        "display": ["Anton"],
        "body": ["Roboto Flex"],
        "label": ["Anton"]
      }
    },
  },
}
